name:                jsonpath-non-determinism
version:             0.1.0.0
github:              "glyn/jsonpath-non-determinism"
license:             BSD-3-Clause
author:              "Glyn Normington"
maintainer:          "glyn.normington@gmail.com"
copyright:           "Glyn Normington"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/glyn/jsonpath-non-determinism#readme>

dependencies:
- base >= 4.7 && < 5
- aeson >= 2.1 && < 2.3
- aeson-qq >= 0.8 && < 0.9
- bytestring >= 0.11 && < 0.12
- containers >= 0.6 && < 0.7
- vector >= 0.13 && < 0.14
- transformers >= 0.6 && < 0.7

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  jsonpath-non-determinism-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jsonpath-non-determinism

tests:
  jsonpath-non-determinism-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jsonpath-non-determinism
